apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ktdb7b1n7-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ktdb7b1n7-nodejs 
  name: ktdb7b1n7-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: ktdb7b1n7-nodejs 
